server:
  port: 8093
  tomcat:
      max-threads: 800
      uri-encoding: UTF-8
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
#eureka:
#  instance:
#    hostname: localhost
#    serverport: 8090
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.serverport}/eureka/
spring:
  application:
    name: client-demo1