server:
                                                           port: 8088
                                                           tomcat:
                                                               max-threads: 800
                                                               uri-encoding: UTF-8
                                                         eureka:
                                                           server:
                                                             enableSelfPreservation: false
                                                           instance:
                                                             hostname: localhost
                                                           client:
                                                             registerWithEureka: true
                                                             fetchRegistry: true
                                                             serviceUrl:
                                                               defaultZone: http://localhost:8088/eureka,http://localhost:8087/eureka
                                                         spring:
                                                           application:
                                                             name: servertwo